import type { ProgrammeType, ProgrammeSession, MediaType } from '@/types/database';

interface MockSermon {
  id: string;
  title: string;
  pastor: string;
  pastorId: string;
  date: string;
  year: number;
  duration: number;
  thumbnailUrl: string | null;
  tags: string[];
  isFree: boolean;
  viewCount: number;
  seriesId: string | null;
  mediaType: MediaType;
  programmeType: ProgrammeType;
  specialProgrammeName: string | null;
  threeDgDay: 1 | 2 | 3 | null;
  programmeSession: ProgrammeSession | null;
}

export const MOCK_SERMONS: MockSermon[] = [
  // ── 2025 ──────────────────────────────────

  // Sunday Services
  {
    id: '1',
    title: 'Finding Peace in the Storm',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '6 Apr 2025',
    year: 2025,
    duration: 2760,
    thumbnailUrl: null,
    tags: ['Peace', 'Faith', 'Anxiety'],
    isFree: false,
    viewCount: 1240,
    mediaType: 'video',
    seriesId: '1',
    programmeType: 'sunday_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '3',
    title: 'Walking in Purpose',
    pastor: 'Min Joseph Sanni',
    pastorId: '3',
    date: '30 Mar 2025',
    year: 2025,
    duration: 2100,
    thumbnailUrl: null,
    tags: ['Purpose', 'Destiny'],
    isFree: true,
    viewCount: 1560,
    mediaType: 'video',
    seriesId: '3',
    programmeType: 'sunday_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '7',
    title: 'Covenant Promises',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '16 Feb 2025',
    year: 2025,
    duration: 2580,
    thumbnailUrl: null,
    tags: ['Covenant', 'Promises', 'Faith'],
    isFree: false,
    viewCount: 720,
    mediaType: 'video',
    seriesId: '2',
    programmeType: 'sunday_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '8',
    title: 'Overcoming Fear Through Faith',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '9 Feb 2025',
    year: 2025,
    duration: 2640,
    thumbnailUrl: null,
    tags: ['Fear', 'Faith', 'Trust'],
    isFree: true,
    viewCount: 2100,
    mediaType: 'video',
    seriesId: '2',
    programmeType: 'sunday_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },

  // Midweek Services
  {
    id: '2',
    title: 'Power of Prayer',
    pastor: 'Dr Seun Olabode',
    pastorId: '2',
    date: '2 Apr 2025',
    year: 2025,
    duration: 2340,
    thumbnailUrl: null,
    tags: ['Prayer', 'Faith'],
    isFree: true,
    viewCount: 890,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'midweek_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '19',
    title: 'Abiding in the Vine',
    pastor: 'Dr Seun Olabode',
    pastorId: '2',
    date: '19 Mar 2025',
    year: 2025,
    duration: 2100,
    thumbnailUrl: null,
    tags: ['Abiding', 'Growth', 'Fruit'],
    isFree: true,
    viewCount: 540,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'midweek_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },

  // 3DG April 2025 (series)
  {
    id: '20',
    title: 'Open Heavens — Day 1 Morning',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '1 Apr 2025',
    year: 2025,
    duration: 3600,
    thumbnailUrl: null,
    tags: ['Glory', 'Open Heavens'],
    isFree: true,
    viewCount: 2800,
    mediaType: 'video',
    seriesId: '4',
    programmeType: '3dg',
    specialProgrammeName: null,
    threeDgDay: 1,
    programmeSession: 'morning',
  },
  {
    id: '21',
    title: 'Open Heavens — Day 1 Evening',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '1 Apr 2025',
    year: 2025,
    duration: 3300,
    thumbnailUrl: null,
    tags: ['Glory', 'Fire', 'Deliverance'],
    isFree: true,
    viewCount: 2600,
    mediaType: 'video',
    seriesId: '4',
    programmeType: '3dg',
    specialProgrammeName: null,
    threeDgDay: 1,
    programmeSession: 'evening',
  },
  {
    id: '22',
    title: 'Open Heavens — Day 2 Morning',
    pastor: 'Dr Seun Olabode',
    pastorId: '2',
    date: '2 Apr 2025',
    year: 2025,
    duration: 3400,
    thumbnailUrl: null,
    tags: ['Glory', 'Healing'],
    isFree: true,
    viewCount: 2200,
    mediaType: 'video',
    seriesId: '4',
    programmeType: '3dg',
    specialProgrammeName: null,
    threeDgDay: 2,
    programmeSession: 'morning',
  },
  {
    id: '23',
    title: 'Open Heavens — Day 2 Evening',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '2 Apr 2025',
    year: 2025,
    duration: 3500,
    thumbnailUrl: null,
    tags: ['Glory', 'Breakthrough'],
    isFree: true,
    viewCount: 2400,
    mediaType: 'video',
    seriesId: '4',
    programmeType: '3dg',
    specialProgrammeName: null,
    threeDgDay: 2,
    programmeSession: 'evening',
  },
  {
    id: '24',
    title: 'Open Heavens — Day 3 Morning',
    pastor: 'Min Joseph Sanni',
    pastorId: '3',
    date: '3 Apr 2025',
    year: 2025,
    duration: 3200,
    thumbnailUrl: null,
    tags: ['Glory', 'Declaration'],
    isFree: true,
    viewCount: 2000,
    mediaType: 'video',
    seriesId: '4',
    programmeType: '3dg',
    specialProgrammeName: null,
    threeDgDay: 3,
    programmeSession: 'morning',
  },
  {
    id: '25',
    title: 'Open Heavens — Day 3 Evening',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '3 Apr 2025',
    year: 2025,
    duration: 3800,
    thumbnailUrl: null,
    tags: ['Glory', 'Impartation', 'Fire'],
    isFree: true,
    viewCount: 3100,
    mediaType: 'video',
    seriesId: '4',
    programmeType: '3dg',
    specialProgrammeName: null,
    threeDgDay: 3,
    programmeSession: 'evening',
  },

  // Morning by Morning (Mon-Fri daily devotionals)
  {
    id: '26',
    title: 'Start Your Day With God — Monday',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '7 Apr 2025',
    year: 2025,
    duration: 900,
    thumbnailUrl: null,
    tags: ['Devotion', 'Morning', 'Faith'],
    isFree: true,
    viewCount: 450,
    mediaType: 'audio',
    seriesId: null,
    programmeType: 'morning_by_morning',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '27',
    title: 'Start Your Day With God — Tuesday',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '8 Apr 2025',
    year: 2025,
    duration: 840,
    thumbnailUrl: null,
    tags: ['Devotion', 'Morning', 'Trust'],
    isFree: true,
    viewCount: 380,
    mediaType: 'audio',
    seriesId: null,
    programmeType: 'morning_by_morning',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '28',
    title: 'Start Your Day With God — Wednesday',
    pastor: 'Dr Seun Olabode',
    pastorId: '2',
    date: '9 Apr 2025',
    year: 2025,
    duration: 780,
    thumbnailUrl: null,
    tags: ['Devotion', 'Morning', 'Peace'],
    isFree: true,
    viewCount: 340,
    mediaType: 'audio',
    seriesId: null,
    programmeType: 'morning_by_morning',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },

  // TOD (Throne of David — Saturday prayer)
  {
    id: '29',
    title: 'Throne of David — Warfare Prayers',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '5 Apr 2025',
    year: 2025,
    duration: 3600,
    thumbnailUrl: null,
    tags: ['Prayer', 'Warfare', 'Intercession'],
    isFree: true,
    viewCount: 680,
    mediaType: 'audio',
    seriesId: null,
    programmeType: 'tod',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '30',
    title: 'Throne of David — Declarations',
    pastor: 'Dr Seun Olabode',
    pastorId: '2',
    date: '29 Mar 2025',
    year: 2025,
    duration: 3000,
    thumbnailUrl: null,
    tags: ['Prayer', 'Declarations', 'Prophecy'],
    isFree: true,
    viewCount: 520,
    mediaType: 'audio',
    seriesId: null,
    programmeType: 'tod',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },

  // Rev Gbeniyi Eboda
  {
    id: '31',
    title: 'The Blood Covenant',
    pastor: 'Rev Gbeniyi Eboda',
    pastorId: '4',
    date: '23 Mar 2025',
    year: 2025,
    duration: 2700,
    thumbnailUrl: null,
    tags: ['Covenant', 'Blood', 'Redemption'],
    isFree: true,
    viewCount: 920,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'sunday_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '32',
    title: 'Standing on the Promises',
    pastor: 'Rev Gbeniyi Eboda',
    pastorId: '4',
    date: '12 Jan 2025',
    year: 2025,
    duration: 2400,
    thumbnailUrl: null,
    tags: ['Promises', 'Faith', 'Patience'],
    isFree: true,
    viewCount: 780,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'midweek_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },

  // Pastor Korede Komaya
  {
    id: '33',
    title: 'The Heart of Worship',
    pastor: 'Pst Korede Komaya',
    pastorId: '5',
    date: '16 Mar 2025',
    year: 2025,
    duration: 2280,
    thumbnailUrl: null,
    tags: ['Worship', 'Heart', 'Surrender'],
    isFree: true,
    viewCount: 640,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'sunday_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '34',
    title: 'Living a Life of Impact',
    pastor: 'Pst Korede Komaya',
    pastorId: '5',
    date: '5 Feb 2025',
    year: 2025,
    duration: 2100,
    thumbnailUrl: null,
    tags: ['Impact', 'Purpose', 'Service'],
    isFree: true,
    viewCount: 510,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'midweek_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },

  // ── 2024 ──────────────────────────────────

  {
    id: '9',
    title: 'The Grace That Sustains',
    pastor: 'Dr Seun Olabode',
    pastorId: '2',
    date: '15 Dec 2024',
    year: 2024,
    duration: 2340,
    thumbnailUrl: null,
    tags: ['Grace', 'Mercy'],
    isFree: false,
    viewCount: 950,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'sunday_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '10',
    title: 'Healing in His Wings',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '8 Dec 2024',
    year: 2024,
    duration: 2700,
    thumbnailUrl: null,
    tags: ['Healing', 'Faith'],
    isFree: true,
    viewCount: 1800,
    mediaType: 'video',
    seriesId: '1',
    programmeType: 'sunday_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '11',
    title: 'The Joy of Giving',
    pastor: 'Min Joseph Sanni',
    pastorId: '3',
    date: '20 Nov 2024',
    year: 2024,
    duration: 1980,
    thumbnailUrl: null,
    tags: ['Giving', 'Generosity'],
    isFree: true,
    viewCount: 670,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'midweek_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '12',
    title: 'Christmas Special — The Gift of Emmanuel',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '25 Dec 2024',
    year: 2024,
    duration: 3000,
    thumbnailUrl: null,
    tags: ['Christmas', 'Love', 'Salvation'],
    isFree: true,
    viewCount: 3200,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'special',
    specialProgrammeName: 'Christmas Service 2024',
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '13',
    title: 'New Year Crossover Night',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '31 Dec 2024',
    year: 2024,
    duration: 5400,
    thumbnailUrl: null,
    tags: ['New Year', 'Prophecy', 'Declaration'],
    isFree: true,
    viewCount: 4100,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'special',
    specialProgrammeName: 'Crossover Night 2024',
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '14',
    title: 'EHCC Annual Convention — Day 1',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '10 Oct 2024',
    year: 2024,
    duration: 4200,
    thumbnailUrl: null,
    tags: ['Convention', 'Vision', 'Growth'],
    isFree: false,
    viewCount: 1500,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'special',
    specialProgrammeName: '2024 Annual Convention',
    threeDgDay: null,
    programmeSession: null,
  },

  // ── 2023 ──────────────────────────────────

  {
    id: '15',
    title: 'Foundations of Faith',
    pastor: 'Rev Deji Olabode',
    pastorId: '1',
    date: '5 Nov 2023',
    year: 2023,
    duration: 2700,
    thumbnailUrl: null,
    tags: ['Faith', 'Foundation', 'Growth'],
    isFree: true,
    viewCount: 3400,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'sunday_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
  {
    id: '16',
    title: 'The Power of the Tongue',
    pastor: 'Dr Seun Olabode',
    pastorId: '2',
    date: '18 Oct 2023',
    year: 2023,
    duration: 2400,
    thumbnailUrl: null,
    tags: ['Words', 'Wisdom', 'Power'],
    isFree: true,
    viewCount: 2800,
    mediaType: 'video',
    seriesId: null,
    programmeType: 'midweek_service',
    specialProgrammeName: null,
    threeDgDay: null,
    programmeSession: null,
  },
];

export const MOCK_SERIES = [
  {
    id: '1',
    title: 'Finding Peace',
    description: 'A four-part series on discovering God\'s peace in every season of life. Pastor Emmanuel takes us through the storms and into the calm.',
    episodeCount: 4,
    thumbnailUrl: null,
    isActive: true,
    sermonIds: ['1', '10'],
  },
  {
    id: '2',
    title: 'Power of Faith',
    description: 'What does it mean to truly walk by faith? This six-part series explores the foundations, the challenges, and the rewards of a faith-filled life.',
    episodeCount: 6,
    thumbnailUrl: null,
    isActive: true,
    sermonIds: ['7', '8'],
  },
  {
    id: '3',
    title: 'Walking in Purpose',
    description: 'Discover the unique calling God has placed on your life. Three powerful messages on destiny, direction, and divine purpose.',
    episodeCount: 3,
    thumbnailUrl: null,
    isActive: false,
    sermonIds: ['3'],
  },
  {
    id: '4',
    title: '3DG April 2025 — Open Heavens',
    description: 'Three Days of Glory, April 2025. Six powerful sessions of glory, fire, healing, and impartation across three days.',
    episodeCount: 6,
    thumbnailUrl: null,
    isActive: true,
    sermonIds: ['20', '21', '22', '23', '24', '25'],
  },
];

export const MOCK_PASTORS = [
  {
    id: '1',
    name: 'Rev Deji Olabode',
    shortName: 'RDO',
    initials: 'RDO',
    bio: 'Senior Pastor of Enthronement House Christian Center. A passionate teacher of the Word, Rev Deji Olabode\'s sermons on faith, peace, and God\'s promises have touched thousands of lives across Nigeria and beyond.',
    photoUrl: '/images/pastors/rev-deji-olabode.jpg',
    churchRole: 'Senior Pastor',
    sermonCount: 15,
  },
  {
    id: '2',
    name: 'Dr Seun Olabode',
    shortName: 'Dr Seun',
    initials: 'SO',
    bio: 'Co-Pastor of Enthronement House Christian Center. Dr Seun Olabode brings a unique depth to her teaching on prayer, grace, and spiritual growth, leading the women\'s ministry with wisdom and compassion.',
    photoUrl: '/images/pastors/rev-deji-olabode.jpg',
    churchRole: 'Co-Pastor',
    sermonCount: 7,
  },
  {
    id: '3',
    name: 'Minister Joseph Sanni',
    shortName: 'Min Sanni',
    initials: 'JS',
    bio: 'Minister at Enthronement House Christian Center. Minister Joseph Sanni connects with the congregation through powerful messages on purpose, identity, and generosity.',
    photoUrl: null,
    churchRole: 'Minister',
    sermonCount: 4,
  },
  {
    id: '4',
    name: 'Rev Gbeniyi Eboda',
    shortName: 'Rev Eboda',
    initials: 'GE',
    bio: 'Reverend at Enthronement House Christian Center. Rev Gbeniyi Eboda is a gifted teacher whose messages on covenant, faith, and the promises of God bring clarity and conviction.',
    photoUrl: null,
    churchRole: 'Reverend',
    sermonCount: 2,
  },
  {
    id: '5',
    name: 'Pastor Korede Komaya',
    shortName: 'Pst Korede',
    initials: 'KK',
    bio: 'Pastor at Enthronement House Christian Center. Pastor Korede Komaya ministers with passion and depth, reaching hearts through practical and spirit-filled teaching.',
    photoUrl: null,
    churchRole: 'Pastor',
    sermonCount: 2,
  },
];

export const MOCK_CONTINUE_WATCHING = [
  { ...MOCK_SERMONS[0], progress: 35 },
  { ...MOCK_SERMONS[3], progress: 72 },
];

export const AVAILABLE_YEARS = [2025, 2024, 2023];
